"""
Diagnostic script to identify why semantic (Kahulugan) scores are near 0%.
"""
import sys
import os
from pathlib import Path

backend_dir = Path(__file__).resolve().parent
sys.path.append(str(backend_dir))

import numpy as np
from sqlalchemy.orm import Session
from app.models.database import SessionLocal, Sentence
from sentence_transformers import SentenceTransformer

from app.core.config import get_settings
settings = get_settings()

base_path = backend_dir
dapt_path_1 = os.path.join(base_path, 'models', 'rizal-xlm-r-dapt')
dapt_path_2 = os.path.join(base_path, 'app', 'models', 'rizal-xlm-r-dapt')
dapt_path = dapt_path_1 if os.path.exists(dapt_path_1) else (dapt_path_2 if os.path.exists(dapt_path_2) else None)

print(f"DAPT model path: {dapt_path}")

db: Session = SessionLocal()

try:
    buod = db.query(Sentence).filter(Sentence.source_type == 'summary').first()
    full_s = db.query(Sentence).filter(Sentence.source_type == 'full').first()

    print(f"\n--- DB Embedding Info ---")
    if buod is None:
        print("No buod sentences found!")
    else:
        print(f"Buod sentence: {buod.sentence_text[:80]}")
        if buod.embedding is not None:
            buod_emb = np.array(buod.embedding, dtype=np.float32)
            print(f"Buod embedding dim: {buod_emb.shape[0]}")
            print(f"Buod embedding norm: {float(np.linalg.norm(buod_emb)):.4f}")
        else:
            buod_emb = None
            print("Buod embedding: None in DB!")

    if full_s is None:
        print("No full sentences found!")
    else:
        print(f"\nFull sentence: {full_s.sentence_text[:80]}")
        if full_s.embedding is not None:
            full_emb = np.array(full_s.embedding, dtype=np.float32)
            print(f"Full embedding dim: {full_emb.shape[0]}")
            print(f"Full embedding norm: {float(np.linalg.norm(full_emb)):.4f}")
        else:
            full_emb = None
            print("Full embedding: None in DB!")

    if dapt_path:
        print(f"\n--- Current DAPT Model Output ---")
        model = SentenceTransformer(dapt_path)
        sample = "Isang pagtitipon ang gaganapin."
        test_emb = model.encode(sample, show_progress_bar=False)
        print(f"DAPT model output dim: {len(test_emb)}")
        print(f"DAPT model output norm: {float(np.linalg.norm(test_emb)):.4f}")

        if buod is not None and buod.embedding is not None:
            fresh_buod = model.encode(buod.sentence_text, show_progress_bar=False)
            b_stored = buod_emb / (float(np.linalg.norm(buod_emb)) + 1e-9)
            b_fresh = fresh_buod / (float(np.linalg.norm(fresh_buod)) + 1e-9)
            
            if b_stored.shape[0] == b_fresh.shape[0]:
                cos = float(np.dot(b_stored, b_fresh))
                print(f"\nCosine sim (stored buod emb vs freshly encoded by DAPT): {cos:.4f}")
                if cos < 0.5:
                    print("❌ MISMATCH: DB embeddings were generated by a DIFFERENT model!")
                    print("   FIX: Reseed the database using seed_db.py and seed_full_db.py")
                else:
                    print("✅ DB embeddings match the current DAPT model output space.")
            else:
                print(f"\n❌ DIMENSION MISMATCH: stored={b_stored.shape[0]}, DAPT={b_fresh.shape[0]}")
                print("   FIX: Reseed the database using seed_db.py and seed_full_db.py")
    else:
        print("\nDAP model not found!")
finally:
    db.close()
    print("\nDone.")
